Traceback (most recent call last):
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\juacevedo.ATLANTICQI\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
encoded_data = encoder.fit_transform(fraud_det[['id_12']])
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(['id_12']))
encoded_df

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
Cell [1;32mIn[12], line 5[0m
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpreprocessing[39;00m [38;5;28;01mimport[39;00m OneHotEncoder
[0;32m      4[0m encoder [38;5;241m=[39m OneHotEncoder(sparse[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m----> 5[0m encoded_data [38;5;241m=[39m encoder[38;5;241m.[39mfit_transform([43mfraud_det[49m[43m[[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mid_12[39;49m[38;5;124;43m'[39;49m[43m][49m[43m][49m)
[0;32m      6[0m encoded_df [38;5;241m=[39m pd[38;5;241m.[39mDataFrame(encoded_data, columns[38;5;241m=[39mencoder[38;5;241m.[39mget_feature_names_out([[38;5;124m'[39m[38;5;124mid_12[39m[38;5;124m'[39m]))
[0;32m      7[0m encoded_df

File [1;32m~\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\pandas\core\frame.py:3813[0m, in [0;36mDataFrame.__getitem__[1;34m(self, key)[0m
[0;32m   3811[0m     [38;5;28;01mif[39;00m is_iterator(key):
[0;32m   3812[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[1;32m-> 3813[0m     indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcolumns[49m[38;5;241;43m.[39;49m[43m_get_indexer_strict[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mcolumns[39;49m[38;5;124;43m"[39;49m[43m)[49m[[38;5;241m1[39m]
[0;32m   3815[0m [38;5;66;03m# take() does not accept boolean indexers[39;00m
[0;32m   3816[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(indexer, [38;5;124m"[39m[38;5;124mdtype[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m) [38;5;241m==[39m [38;5;28mbool[39m:

File [1;32m~\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\pandas\core\indexes\base.py:6070[0m, in [0;36mIndex._get_indexer_strict[1;34m(self, key, axis_name)[0m
[0;32m   6067[0m [38;5;28;01melse[39;00m:
[0;32m   6068[0m     keyarr, indexer, new_indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_reindex_non_unique(keyarr)
[1;32m-> 6070[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_if_missing[49m[43m([49m[43mkeyarr[49m[43m,[49m[43m [49m[43mindexer[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[0;32m   6072[0m keyarr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indexer)
[0;32m   6073[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[0;32m   6074[0m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

File [1;32m~\AppData\Local\miniconda3\envs\ml_venv\lib\site-packages\pandas\core\indexes\base.py:6130[0m, in [0;36mIndex._raise_if_missing[1;34m(self, key, indexer, axis_name)[0m
[0;32m   6128[0m     [38;5;28;01mif[39;00m use_interval_msg:
[0;32m   6129[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[1;32m-> 6130[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m)
[0;32m   6132[0m not_found [38;5;241m=[39m [38;5;28mlist[39m(ensure_index(key)[missing_mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m]][38;5;241m.[39munique())
[0;32m   6133[0m [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[38;5;124m not in index[39m[38;5;124m"[39m)

[1;31mKeyError[0m: "None of [Index(['id_12'], dtype='object')] are in the [columns]"

